[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | env
  | \.env
  | _build
  | buck-out
  | build
  | dist
  | backup_original_structure
  | __pycache__
  | site-packages
)/
'''

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true

# Ignore standard library type issues
[[tool.mypy.overrides]]
module = [
    "posixpath",
    "ntpath", 
    "os.*",
]
ignore_errors = true
