name: unified-order-system
services:
- name: web
  source_dir: /
  github:
    repo: your-username/shipping-gui
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm --bind 0.0.0.0:8080 wsgi:application
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: FLASK_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: VEEQO_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: EASYSHIP_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: FLASK_ENV
    scope: RUN_TIME
    value: production
